/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=relay/wrangler.jsonc --include-runtime=false relay/env.d.ts` (hash: b497a93d70a4d61df55bea08427c1ab8)
interface __BaseEnv_Env {
	ROOM_CREATE_LIMIT: RateLimit;
	ROOM_JOIN_LIMIT: RateLimit;
	SOCKET_MESSAGE_LIMIT: RateLimit;
	ASSETS: Fetcher;
	ROOM: DurableObjectNamespace<import("./worker").Room>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "Room";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
