/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=relay/wrangler.jsonc --include-runtime=false relay/env.d.ts` (hash: 98bc1b3bc092438271b82681d809e7df)
interface __BaseEnv_Env {
	ROOM_CREATE_LIMIT: RateLimit;
	ROOM_JOIN_LIMIT: RateLimit;
	SOCKET_MESSAGE_LIMIT: RateLimit;
	ASSETS: Fetcher;
	TURN_KEY_ID: "7339df54ca223e7cbb7693d16193dc9c";
	ROOM: DurableObjectNamespace<import("./worker").Room>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "Room";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
interface Env {
	TURN_KEY_SECRET: string;
}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TURN_KEY_ID">> {}
}
